language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly
  - hhvm
  
matrix:
  allow_failures:
  - php: 7.4snapshot
    env: COMPOSER_FLAGS="--ignore-platform-reqs"
  - php: nightly
    env: COMPOSER_FLAGS="--ignore-platform-reqs"
  - php: hhvm
    env: COMPOSER_FLAGS="--ignore-platform-reqs"

install: composer install --no-interaction --classmap-authoritative --no-suggest ${COMPOSER_FLAGS}

script: vendor/bin/phpunit --configuration phpunit.xml

after_success: vendor/bin/php-coveralls --verbose

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer
