language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly
  
matrix:
  allow_failures:
  - php: 7.4snapshot
  - php: nightly

install: composer update --no-interaction --classmap-authoritative --no-suggest --ignore-platform-reqs --prefer-lowest --no-progress

script: vendor/bin/phpunit --configuration phpunit.xml

after_success: vendor/bin/php-coveralls --verbose

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer
