version: 2.1

orbs:
  composer: stockfiller/composer@0.0.38
  php-cs-fixer: stockfiller/php-cs-fixer@0.0.18
  phpunit: stockfiller/phpunit@0.0.13
  php-coveralls: nekman/php-coveralls@0.0.5

executors:
  php74:
    docker:
      - image: php:7.4-alpine
    resource_class: small
  php80:
    docker:
      - image: php:8.0-alpine
    resource_class: small

jobs:
  test_coverage:
    executor: php74
    steps:
      - run:
          name: Install PCOV and git
          command: |-
            apk add --update --no-cache ${PHPIZE_DEPS} git
            pecl install pcov-1.0.6
            docker-php-ext-enable pcov
      - checkout
      - composer/install_bin
      - composer/install
      - phpunit/test:
          flags: --coverage-clover coverage/clover.xml
      - php-coveralls/upload:
          clover-path: coverage/clover.xml

workflows:
  master:
    jobs:
      - phpunit/test:
          matrix:
            parameters:
              executor:
                - php74
                - php80
          pre-steps: [ composer/install_bin ]
          filters:
            branches:
              only: master
  branch:
    jobs:
      - php-cs-fixer/fix:
          executor: php74
          rules: "@PSR2"
          pre-steps:
            - run: apk add --update --no-cache git openssh-client
            - composer/install_bin
          filters: &branch-filters
            branches:
              ignore: master
      - test_coverage:
          filters: *branch-filters
          requires: [ php-cs-fixer/fix ]
      - phpunit/test:
          matrix:
            parameters:
              executor:
                - php80
          pre-steps: [ composer/install_bin ]
          filters: *branch-filters
          requires: [ php-cs-fixer/fix ]
